[[language]]
name = "rust"
formatter = { command = "leptosfmt", args = ["--stdin", "--rustfmt"] }

[language-server.rust-analyzer.config]
cargo.features = "all"
# cargo.features = ["ssr", "hydrate", "csr"]
